# api-sports.io team IDs → logo URL: https://media.api-sports.io/football/teams/{id}.png
# Covers all 5 leagues supported by the simulator

TEAM_IDS = {
    # ── Premier League (39) ────────────────────────────────────────────────
    "Manchester City":     50,
    "Arsenal":             42,
    "Liverpool":           40,
    "Chelsea":             49,
    "Tottenham":           47,
    "Aston Villa":         66,
    "Newcastle":           34,
    "Manchester United":   33,
    "Brighton":            51,
    "West Ham":            48,
    "Crystal Palace":      52,
    "Brentford":           55,
    "Fulham":              36,
    "Wolves":              39,
    "Everton":             45,
    "Nottingham Forest":   65,
    "Burnley":             44,
    "Sheffield United":    62,
    "Luton":             1359,
    "Bournemouth":         35,
    "Ipswich":             57,
    "Leicester":           46,
    "Southampton":         41,
    "Leeds":               63,
    "Watford":             38,
    "Norwich":             71,
    "West Brom":           60,

    # ── La Liga (140) ──────────────────────────────────────────────────────
    "Real Madrid":        541,
    "Barcelona":          529,
    "Atletico Madrid":    530,
    "Real Sociedad":      548,
    "Real Betis":         543,
    "Villarreal":         533,
    "Athletic Bilbao":    531,
    "Girona":             547,
    "Valencia":           532,
    "Sevilla":            536,
    "Osasuna":            727,
    "Rayo Vallecano":     728,
    "Getafe":             546,
    "Celta Vigo":         538,
    "Mallorca":           723,
    "Cadiz":              724,
    "Alaves":             720,
    "Las Palmas":         737,
    "Espanol":            540,
    "Valladolid":         720,
    "Levante":            544,
    "Zaragoza":           550,
    "Malaga":             534,
    "Deportivo":          719,

    # ── Serie A (135) ──────────────────────────────────────────────────────
    "Inter":              505,
    "Juventus":           496,
    "AC Milan":           489,
    "Napoli":             492,
    "Roma":               497,
    "Lazio":              487,
    "Atalanta":           499,
    "Fiorentina":         502,
    "Torino":             503,
    "Bologna":            500,
    "Monza":             1579,
    "Empoli":             511,
    "Salernitana":        514,
    "Lecce":              867,
    "Udinese":            494,
    "Frosinone":          512,
    "Verona":             504,
    "Sassuolo":           508,
    "Sampdoria":          507,
    "Cagliari":           490,
    "Genoa":              495,
    "Parma":              498,
    "Spezia":            4528,
    "Cremonese":          519,
    "Venezia":            517,
    "Brescia":            516,

    # ── Bundesliga (78) ────────────────────────────────────────────────────
    "Bayern Munich":       157,
    "Borussia Dortmund":   165,
    "RB Leipzig":          173,
    "Bayer Leverkusen":    168,
    "Eintracht Frankfurt": 169,
    "Stuttgart":           172,
    "Wolfsburg":           161,
    "Borussia M'gladbach": 163,
    "Union Berlin":        182,
    "Freiburg":            160,
    "Augsburg":            170,
    "Hoffenheim":          175,
    "Mainz":               164,
    "Werder Bremen":       162,
    "Heidenheim":          180,
    "Darmstadt":           176,
    "Schalke 04":          167,
    "Hamburg":             180,
    "Hertha Berlin":       159,
    "FC Cologne":          192,
    "Bielefeld":           183,
    "Paderborn":           181,

    # ── Ligue 1 (61) ───────────────────────────────────────────────────────
    "PSG":                  85,
    "Monaco":               91,
    "Marseille":            81,
    "Lyon":                 80,
    "Lille":                79,
    "Nice":                 84,
    "Rennes":               111,
    "Lens":                 116,
    "Nantes":               83,
    "Montpellier":          82,
    "Strasbourg":           95,
    "Reims":                93,
    "Toulouse":             96,
    "Brest":                113,
    "Lorient":              112,
    "Angers":               115,
    "St Etienne":           97,
    "Bordeaux":             77,
    "Auxerre":              109,
    "Metz":                 88,
}
